'use client';

import { useCollection, useDoc, useUser, useFirestore } from '@/firebase';
import { Button } from '@/components/ui/button';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '@/components/ui/accordion';
import {
  Briefcase,
  Car,
  ChevronRight,
  CreditCard,
  Dog,
  Dumbbell,
  Flame,
  Gift,
  GraduationCap,
  Heart,
  Home,
  Landmark,
  Lightbulb,
  MoreHorizontal,
  Phone,
  PiggyBank,
  Plane,
  Shield,
  ShieldAlert,
  Shirt,
  ShoppingBasket,
  Smile,
  Sparkles,
  Tv,
  Users,
  Wallet,
  Wifi,
  Wrench,
  Droplet,
  Edit,
  Baby,
  Hammer,
  Bike,
  User,
  FileText,
  ArrowLeft,
  type LucideIcon,
} from 'lucide-react';
import Link from 'next/link';
import { useMemo, useEffect, useRef, useCallback, useState } from 'react';
import type { DocumentData, Timestamp as FirestoreTimestamp } from 'firebase/firestore';
import { collection, query, where, getDocs, setDoc, doc, addDoc, Timestamp } from 'firebase/firestore';
import { startOfWeek, endOfWeek, isWithinInterval, format, subWeeks, isBefore, addWeeks, addMonths, addYears } from 'date-fns';
import { cn } from '@/lib/utils';
import { PageHeader } from '@/components/PageHeader';
import { HamburgerMenu } from '@/components/HamburgerMenu';
import { BottomNav } from '@/components/BottomNav';
import { formatCurrency, getWeeklyAmount } from '@/lib/format';
import type { Frequency } from '@/lib/constants';

// Data Interfaces
interface IncomeSource extends DocumentData {
  id: string;
  name: string;
  amount: number;
  frequency: Frequency;
}

interface RequiredExpense extends DocumentData {
  id: string;
  category: string;
  name?: string;
  amount: number;
  frequency: Frequency;
}

interface DiscretionaryExpense extends DocumentData {
  id: string;
  category: string;
  name?: string;
  plannedAmount: number;
}

interface Loan extends DocumentData {
  id: string;
  name: string;
  category: string;
  totalBalance: number;
}

interface SavingsGoal extends DocumentData {
  id: string;
  name: string;
  category: string;
  targetAmount: number;
  currentAmount: number;
}

interface Transaction extends DocumentData {
  id: string;
  type: 'Income' | 'Expense';
  amount: number;
  date: FirestoreTimestamp;
  category: string;
  description?: string;
  autoGenerated?: boolean;
  sourceId?: string;
}

interface UserProfile extends DocumentData {
  startDayOfWeek?: 'Sunday' | 'Monday' | 'Tuesday' | 'Wednesday' | 'Thursday' | 'Friday' | 'Saturday';
}

// Icon Mappings
const essentialExpenseIcons: Record<string, LucideIcon> = {
  'Groceries': ShoppingBasket, 'Rent/Mortgage': Home, 'Natural Gas': Flame,
  'Electrical': Lightbulb, 'Water/Sewer': Droplet, 'Garbage': MoreHorizontal,
  'Phone': Phone, 'Gas/Parking/Tolls': Car, 'Auto Insurance': Shield,
  'Auto Maintenance': Wrench, 'Auto Registration': FileText, 'Medical': Heart,
  'Dental': Smile, 'Miscellaneous': MoreHorizontal,
};

const discretionaryExpenseIcons: Record<string, LucideIcon> = {
  'Personal Care': Sparkles, 'Apparel': Shirt, 'House Maintenance': Hammer,
  'TV Service': Tv, 'Internet': Wifi, 'Children Activities': Baby,
  'Date Activities': Heart, 'Family Activities': Users, 'Vacation': Plane,
  'Fitness': Dumbbell, 'Gifts': Gift, 'Pets': Dog, 'Subscriptions': CreditCard,
  'Personal Expenses': User, 'Miscellaneous': MoreHorizontal,
};

const loanIcons: Record<string, LucideIcon> = {
  'Credit Cards': CreditCard, 'Auto Loan': Car, 'Home Mortgages': Home,
  'Student Loan': GraduationCap, 'Miscellaneous': MoreHorizontal,
};

const savingsGoalIcons: Record<string, LucideIcon> = {
  'Emergency Fund': ShieldAlert, 'House Purchase': Home, 'Automobile': Car,
  'Vacation': Plane, 'Recreation Equipment': Bike, 'Education': GraduationCap,
  'Miscellaneous': MoreHorizontal, 'Income Balance': Wallet,
};

// Budget Balance Circle
const BudgetBalanceCircle = ({
  amount,
  label,
  isHealthy,
}: {
  amount: number;
  label: string;
  isHealthy: boolean;
}) => {
  const color = isHealthy ? 'hsl(142, 76%, 45%)' : 'hsl(0, 62.8%, 50%)';

  return (
    <div className="flex flex-col items-center gap-1">
      <div className="relative">
        <svg width={80} height={80} className="transform -rotate-90">
          <circle cx={40} cy={40} r={36} fill="none" stroke="hsl(var(--muted) / 0.3)" strokeWidth={8} />
          <circle cx={40} cy={40} r={36} fill="none" stroke={color} strokeWidth={8}
            strokeDasharray={`${2 * Math.PI * 36}`} strokeLinecap="round" />
        </svg>
        <div className="absolute inset-0 flex flex-col items-center justify-center">
          <p className={cn("text-xs font-black tracking-tight font-headline", isHealthy ? "text-green-500" : "text-red-500")}>
            {formatCurrency(amount)}
          </p>
        </div>
      </div>
      <p className="text-[10px] text-muted-foreground text-center leading-tight max-w-20 font-medium">{label}</p>
    </div>
  );
};

// Health Indicator Dot
const HealthDot = ({ isHealthy, label }: { isHealthy: boolean; label: string }) => (
  <div className="flex flex-col items-center gap-1">
    <div className={cn("rounded-full size-10", isHealthy ? "bg-green-500" : "bg-red-500")} />
    <p className="text-[10px] text-muted-foreground text-center leading-tight max-w-16 font-medium">{label}</p>
  </div>
);

// Accordion state localStorage key
const ACCORDION_STATE_KEY = 'wkly_home_accordion_state';

export default function DashboardScreen() {
  const { user } = useUser();
  const firestore = useFirestore();
  const hasCheckedSummaries = useRef(false);
  const hasGeneratedRecurring = useRef(false);
  const dayIndexMap: Record<string, 0 | 1 | 2 | 3 | 4 | 5 | 6> = {
    Sunday: 0, Monday: 1, Tuesday: 2, Wednesday: 3, Thursday: 4, Friday: 5, Saturday: 6
  };

  // Accordion state
  const [expandedItems, setExpandedItems] = useState<string[]>([]);
  const [isInitialized, setIsInitialized] = useState(false);

  useEffect(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem(ACCORDION_STATE_KEY);
      if (saved) {
        try { setExpandedItems(JSON.parse(saved)); } catch { setExpandedItems([]); }
      }
      setIsInitialized(true);
    }
  }, []);

  useEffect(() => {
    if (isInitialized && typeof window !== 'undefined') {
      localStorage.setItem(ACCORDION_STATE_KEY, JSON.stringify(expandedItems));
    }
  }, [expandedItems, isInitialized]);

  // Firestore paths
  const userProfilePath = useMemo(() => (user ? `users/${user.uid}` : null), [user]);
  const incomeSourcesPath = useMemo(() => (user ? `users/${user.uid}/incomeSources` : null), [user]);
  const requiredExpensesPath = useMemo(() => (user ? `users/${user.uid}/requiredExpenses` : null), [user]);
  const discretionaryExpensesPath = useMemo(() => (user ? `users/${user.uid}/discretionaryExpenses` : null), [user]);
  const loansPath = useMemo(() => (user ? `users/${user.uid}/loans` : null), [user]);
  const savingsGoalsPath = useMemo(() => (user ? `users/${user.uid}/savingsGoals` : null), [user]);

  const { data: userProfile } = useDoc<UserProfile>(userProfilePath);
  const { data: incomeSources } = useCollection<IncomeSource>(incomeSourcesPath);
  const { data: requiredExpenses } = useCollection<RequiredExpense>(requiredExpensesPath);
  const { data: discretionaryExpenses } = useCollection<DiscretionaryExpense>(discretionaryExpensesPath);
  const { data: loans } = useCollection<Loan>(loansPath);
  const { data: savingsGoals } = useCollection<SavingsGoal>(savingsGoalsPath);

  // Calculations
  const totalWeeklyIncome = useMemo(() => {
    return (incomeSources || []).reduce((t, s) => t + getWeeklyAmount(s.amount, s.frequency), 0);
  }, [incomeSources]);

  const totalWeeklyRequired = useMemo(() => {
    return (requiredExpenses || []).reduce((t, e) => t + getWeeklyAmount(e.amount, e.frequency), 0);
  }, [requiredExpenses]);

  const totalWeeklyDiscretionary = useMemo(() => {
    return (discretionaryExpenses || []).reduce((t, e) => t + e.plannedAmount, 0);
  }, [discretionaryExpenses]);

  const totalDebt = useMemo(() => {
    return (loans || []).reduce((t, l) => t + l.totalBalance, 0);
  }, [loans]);

  const totalSavingsTarget = useMemo(() => {
    return (savingsGoals || []).filter(g => g.category !== 'Income Balance').reduce((t, g) => t + g.targetAmount, 0);
  }, [savingsGoals]);

  const totalSaved = useMemo(() => {
    return (savingsGoals || []).filter(g => g.category !== 'Income Balance').reduce((t, g) => t + g.currentAmount, 0);
  }, [savingsGoals]);

  const weeklyBalance = totalWeeklyIncome - totalWeeklyRequired - totalWeeklyDiscretionary;

  // Health indicators
  const essentialHealthy = totalWeeklyRequired <= totalWeeklyIncome * 0.5 || totalWeeklyRequired === 0;
  const discretionaryHealthy = totalWeeklyDiscretionary <= totalWeeklyIncome * 0.3 || totalWeeklyDiscretionary === 0;
  const loansHealthy = true; // Would check delinquency
  const savingsHealthy = totalSavingsTarget === 0 || totalSaved >= totalSavingsTarget * 0.1;

  // Auto-generate weekly summaries
  const generateMissingSummaries = useCallback(async () => {
    if (!firestore || !user || !userProfile || hasCheckedSummaries.current) return;
    try {
      const startDay = userProfile?.startDayOfWeek || 'Sunday';
      const weekStartsOn = dayIndexMap[startDay];
      const now = new Date();
      const currentWeekStart = startOfWeek(now, { weekStartsOn });
      const summariesRef = collection(firestore, `users/${user.uid}/weeklySummaries`);
      const summariesSnapshot = await getDocs(summariesRef);
      const existingSummaryDates = new Set(summariesSnapshot.docs.map(d => d.data().weekStartDate));
      const transactionsRef = collection(firestore, `users/${user.uid}/transactions`);
      const transactionsSnapshot = await getDocs(transactionsRef);
      const allTransactions = transactionsSnapshot.docs.map(d => ({ id: d.id, ...d.data() })) as Transaction[];

      for (let i = 1; i <= 12; i++) {
        const weekStart = subWeeks(currentWeekStart, i);
        const weekEnd = endOfWeek(weekStart, { weekStartsOn });
        const weekStartStr = format(weekStart, 'yyyy-MM-dd');
        const weekEndStr = format(weekEnd, 'yyyy-MM-dd');
        if (existingSummaryDates.has(weekStartStr)) continue;

        let totalIncome = 0, totalExpenses = 0;
        for (const t of allTransactions) {
          if (!t.date) continue;
          const txDate = t.date.toDate();
          if (isWithinInterval(txDate, { start: weekStart, end: weekEnd })) {
            if (t.type === 'Income') totalIncome += t.amount;
            else totalExpenses += t.amount;
          }
        }
        if (totalIncome > 0 || totalExpenses > 0) {
          const summaryDoc = doc(firestore, `users/${user.uid}/weeklySummaries`, weekStartStr);
          await setDoc(summaryDoc, { weekStartDate: weekStartStr, weekEndDate: weekEndStr, totalIncome, totalExpenses, createdAt: new Date().toISOString(), userProfileId: user.uid });
        }
      }
      hasCheckedSummaries.current = true;
    } catch (error) { console.error('Error generating weekly summaries:', error); }
  }, [firestore, user, userProfile, dayIndexMap]);

  useEffect(() => {
    if (user && userProfile && firestore) generateMissingSummaries();
  }, [user, userProfile, firestore, generateMissingSummaries]);

  // Auto-generate recurring transactions
  const generateRecurringTransactions = useCallback(async () => {
    if (!firestore || !user || !incomeSources || hasGeneratedRecurring.current) return;
    try {
      const transactionsRef = collection(firestore, `users/${user.uid}/transactions`);
      const now = new Date();
      let created = 0;
      for (const source of incomeSources) {
        const existingQuery = query(transactionsRef, where('autoGenerated', '==', true), where('sourceId', '==', source.id));
        const existingSnapshot = await getDocs(existingQuery);
        const existingTxs = existingSnapshot.docs.map(d => ({ ...d.data(), date: d.data().date?.toDate() }));

        let lastDate: Date | null = null;
        for (const t of existingTxs) { if (t.date && (!lastDate || t.date > lastDate)) lastDate = t.date; }
        if (!lastDate) lastDate = subWeeks(now, 8);

        const getNextDate = (date: Date, freq: string): Date => {
          switch (freq) {
            case 'Weekly': return addWeeks(date, 1);
            case 'Bi-Weekly': return addWeeks(date, 2);
            case 'Monthly': return addMonths(date, 1);
            case 'Yearly': return addYears(date, 1);
            default: return addMonths(date, 1);
          }
        };

        let nextDate = getNextDate(lastDate, source.frequency);
        while (isBefore(nextDate, now)) {
          await addDoc(transactionsRef, { type: 'Income', amount: source.amount, description: `${source.name} (auto-generated)`, category: 'Income', date: Timestamp.fromDate(nextDate), createdAt: Timestamp.now(), autoGenerated: true, sourceId: source.id, userProfileId: user.uid });
          created++;
          nextDate = getNextDate(nextDate, source.frequency);
        }
      }
      if (created > 0) console.log(`Auto-generated ${created} recurring income transactions`);
      hasGeneratedRecurring.current = true;
    } catch (error) { console.error('Error generating recurring transactions:', error); }
  }, [firestore, user, incomeSources]);

  useEffect(() => {
    if (user && firestore && incomeSources && incomeSources.length > 0) generateRecurringTransactions();
  }, [user, firestore, incomeSources, generateRecurringTransactions]);

  // Render list item for accordion
  const renderListItem = (key: string, Icon: LucideIcon, primaryText: string, secondaryText: string | React.ReactNode) => (
    <div key={key} className="flex items-center gap-4 py-3">
      <div className="flex items-center justify-center rounded-lg bg-muted text-foreground shrink-0 size-10 border">
        <Icon className="size-5" />
      </div>
      <div className="flex-1 min-w-0">
        <p className="text-foreground font-semibold truncate">{primaryText}</p>
        <div className="text-sm text-muted-foreground">{secondaryText}</div>
      </div>
      <ChevronRight className="size-5 text-muted-foreground" />
    </div>
  );

  return (
    <div className="bg-background font-headline antialiased min-h-screen flex flex-col">
      <PageHeader
        title="HOME"
        rightContent={<HamburgerMenu />}
      />

      <main className="flex-1 overflow-y-auto no-scrollbar px-4 pb-48 space-y-4 pt-4">
        {/* My Health Score */}
        <div className="bg-card rounded-xl p-4 border shadow-sm">
          <h3 className="text-sm font-bold text-muted-foreground uppercase tracking-wider text-center mb-4">
            My Health Score
          </h3>
          <div className="flex justify-around items-start">
            <BudgetBalanceCircle
              amount={weeklyBalance}
              label="Total Weekly Budget Balance"
              isHealthy={weeklyBalance >= 0}
            />
            <BudgetBalanceCircle
              amount={totalWeeklyIncome}
              label="Total Weekly Income"
              isHealthy={true}
            />
            <HealthDot isHealthy={essentialHealthy} label="My Essential Expenses" />
            <HealthDot isHealthy={discretionaryHealthy} label="My Discretionary Expenses" />
            <HealthDot isHealthy={loansHealthy} label="My Loans" />
            <HealthDot isHealthy={savingsHealthy} label="My Savings Goals" />
          </div>
        </div>

        {/* My Budget Plan */}
        <div className="bg-card rounded-xl border shadow-sm p-4">
          <h3 className="text-sm font-bold text-muted-foreground uppercase tracking-wider text-center mb-3">
            My Budget Plan
          </h3>

          <Accordion
            type="multiple"
            value={expandedItems}
            onValueChange={setExpandedItems}
            className="w-full space-y-2"
          >
            {/* My Income */}
            <AccordionItem value="item-1" className="glass rounded-2xl px-4">
              <AccordionTrigger className="py-4">
                <div className="flex items-center gap-3">
                  <div className="w-8 h-8 rounded-xl gradient-primary flex items-center justify-center">
                    <Wallet className="text-white size-4" />
                  </div>
                  <div className="text-left">
                    <p className="font-semibold text-foreground">My Income</p>
                    <p className="text-xs text-muted-foreground">{formatCurrency(totalWeeklyIncome)} / week</p>
                  </div>
                </div>
              </AccordionTrigger>
              <AccordionContent className="divide-y border-t">
                <div className="pt-2 pb-3">
                  <Button variant="outline" className="w-full" asChild>
                    <Link href="/income"><Edit className="mr-2 size-4" /> Edit My Income</Link>
                  </Button>
                </div>
                {incomeSources?.map((item) =>
                  renderListItem(item.id, Briefcase, item.name, `${formatCurrency(item.amount)} ${item.frequency}`)
                )}
              </AccordionContent>
            </AccordionItem>

            {/* My Essential Expenses */}
            <AccordionItem value="item-2" className="glass rounded-2xl px-4">
              <AccordionTrigger className="py-4">
                <div className="flex items-center gap-3">
                  <div className="w-8 h-8 rounded-xl gradient-primary flex items-center justify-center">
                    <Home className="text-white size-4" />
                  </div>
                  <div className="text-left">
                    <p className="font-semibold text-foreground">My Essential Expenses</p>
                    <p className="text-xs text-muted-foreground">{formatCurrency(totalWeeklyRequired)} / week</p>
                  </div>
                </div>
              </AccordionTrigger>
              <AccordionContent className="divide-y border-t">
                <div className="pt-2 pb-3">
                  <Button variant="outline" className="w-full" asChild>
                    <Link href="/essential-expenses"><Edit className="mr-2 size-4" /> Edit My Essential Expenses</Link>
                  </Button>
                </div>
                {requiredExpenses?.map((item) =>
                  renderListItem(item.id, essentialExpenseIcons[item.category] || Wallet, item.name || item.category, `${formatCurrency(item.amount)} ${item.frequency}`)
                )}
              </AccordionContent>
            </AccordionItem>

            {/* My Discretionary Expenses */}
            <AccordionItem value="item-3" className="glass rounded-2xl px-4">
              <AccordionTrigger className="py-4">
                <div className="flex items-center gap-3">
                  <div className="w-8 h-8 rounded-xl gradient-primary flex items-center justify-center">
                    <ShoppingBasket className="text-white size-4" />
                  </div>
                  <div className="text-left">
                    <p className="font-semibold text-foreground">My Discretionary Expenses</p>
                    <p className="text-xs text-muted-foreground">{formatCurrency(totalWeeklyDiscretionary)} / week</p>
                  </div>
                </div>
              </AccordionTrigger>
              <AccordionContent className="divide-y border-t">
                <div className="pt-2 pb-3">
                  <Button variant="outline" className="w-full" asChild>
                    <Link href="/discretionary-expenses"><Edit className="mr-2 size-4" /> Edit My Discretionary Expenses</Link>
                  </Button>
                </div>
                {discretionaryExpenses?.map((item) =>
                  renderListItem(item.id, discretionaryExpenseIcons[item.category] || Wallet, item.name || item.category, `${formatCurrency(item.plannedAmount)} / week`)
                )}
              </AccordionContent>
            </AccordionItem>

            {/* My Loans */}
            <AccordionItem value="item-4" className="glass rounded-2xl px-4">
              <AccordionTrigger className="py-4">
                <div className="flex items-center gap-3">
                  <div className="w-8 h-8 rounded-xl gradient-primary flex items-center justify-center">
                    <Landmark className="text-white size-4" />
                  </div>
                  <div className="text-left">
                    <p className="font-semibold text-foreground">My Loans</p>
                    <p className="text-xs text-muted-foreground">{formatCurrency(totalDebt)} total balance</p>
                  </div>
                </div>
              </AccordionTrigger>
              <AccordionContent className="divide-y border-t">
                <div className="pt-2 pb-3">
                  <Button variant="outline" className="w-full" asChild>
                    <Link href="/loans"><Edit className="mr-2 size-4" /> Edit My Loans</Link>
                  </Button>
                </div>
                {loans?.map((item) =>
                  renderListItem(item.id, loanIcons[item.category] || CreditCard, item.name, `${formatCurrency(item.totalBalance)} balance`)
                )}
              </AccordionContent>
            </AccordionItem>

            {/* My Planned Savings Goals */}
            <AccordionItem value="item-5" className="glass rounded-2xl px-4">
              <AccordionTrigger className="py-4">
                <div className="flex items-center gap-3">
                  <div className="w-8 h-8 rounded-xl gradient-primary flex items-center justify-center">
                    <PiggyBank className="text-white size-4" />
                  </div>
                  <div className="text-left">
                    <p className="font-semibold text-foreground">My Planned Savings Goals</p>
                    <p className="text-xs text-muted-foreground">{formatCurrency(totalSaved)} of {formatCurrency(totalSavingsTarget)} saved</p>
                  </div>
                </div>
              </AccordionTrigger>
              <AccordionContent className="divide-y border-t">
                <div className="pt-2 pb-3">
                  <Button variant="outline" className="w-full" asChild>
                    <Link href="/savings-goals"><Edit className="mr-2 size-4" /> Edit My Planned Savings Goals</Link>
                  </Button>
                </div>
                {savingsGoals
                  ?.filter((g) => g.category !== 'Income Balance')
                  .map((item) =>
                    renderListItem(item.id, savingsGoalIcons[item.category] || PiggyBank, item.name,
                      <div className="flex flex-col">
                        <span>{item.targetAmount > 0 ? `${((item.currentAmount / item.targetAmount) * 100).toFixed(0)}% saved` : '0% saved'}</span>
                        <span className="text-xs text-muted-foreground">{formatCurrency(item.currentAmount)} of {formatCurrency(item.targetAmount)}</span>
                      </div>
                    )
                  )}
              </AccordionContent>
            </AccordionItem>
          </Accordion>
        </div>
      </main>

      {/* Footer Buttons */}
      <div className="fixed bottom-20 left-0 right-0 p-4 bg-gradient-to-t from-background via-background/80 to-transparent pointer-events-none w-full z-10">
        <div className="pointer-events-auto flex gap-3">
          <Button asChild variant="outline" className="flex-1 h-12 text-base font-bold" size="lg">
            <Link href="/savings-goals">
              <ArrowLeft className="mr-2 h-5 w-5" />
              Back to Savings Goals
            </Link>
          </Button>
          <Button asChild className="flex-1 h-12 text-base font-bold shadow-lg" size="lg">
            <Link href="/transaction/new">
              Continue to Transactions
            </Link>
          </Button>
        </div>
      </div>

      <BottomNav />
    </div>
  );
}
